import type { RocketDesign } from './rocket'

export const PRESET_DESIGNS: RocketDesign[] = [
  {
    id: 'preset-single-stage',
    name: 'Single-Stage Sounding Rocket',
    components: [
      {
        id: 'p1-nose',
        type: 'nose-cone',
        name: 'Ogive Nose Cone',
        stage: 1,
        mass: 0.8,
        shape: 'ogive',
        length: 0.5,
        diameter: 0.15,
        dragCoefficient: 0.32,
      },
      {
        id: 'p1-payload',
        type: 'payload',
        name: 'Avionics Bay',
        stage: 1,
        mass: 1.2,
      },
      {
        id: 'p1-body',
        type: 'body-tube',
        name: 'Airframe Tube',
        stage: 1,
        mass: 2.5,
        length: 1.8,
        diameter: 0.15,
      },
      {
        id: 'p1-recovery',
        type: 'recovery',
        name: 'Parachute Bay',
        stage: 1,
        mass: 0.6,
      },
      {
        id: 'p1-fins',
        type: 'fins',
        name: 'Trapezoidal Fin Set',
        stage: 1,
        mass: 0.7,
        count: 4,
        span: 0.12,
        rootChord: 0.2,
        tipChord: 0.08,
      },
      {
        id: 'p1-engine',
        type: 'engine',
        name: 'M-Class Solid Motor',
        stage: 1,
        mass: 3.5,
        propellantMass: 6.0,
        burnTime: 4.5,
        avgThrust: 2800,
        thrustCurveShape: 'regressive',
      },
    ],
  },
  {
    id: 'preset-two-stage',
    name: 'Two-Stage Sounding Rocket',
    components: [
      {
        id: 'p2-nose',
        type: 'nose-cone',
        name: 'Elliptical Nose Cone',
        stage: 2,
        mass: 0.6,
        shape: 'elliptical',
        length: 0.4,
        diameter: 0.12,
        dragCoefficient: 0.29,
      },
      {
        id: 'p2-payload',
        type: 'payload',
        name: 'Sensor Payload',
        stage: 2,
        mass: 0.9,
      },
      {
        id: 'p2-recovery',
        type: 'recovery',
        name: 'Parachute Bay',
        stage: 2,
        mass: 0.4,
      },
      {
        id: 'p2-body-upper',
        type: 'body-tube',
        name: 'Upper Airframe',
        stage: 2,
        mass: 1.4,
        length: 0.9,
        diameter: 0.12,
      },
      {
        id: 'p2-fins-upper',
        type: 'fins',
        name: 'Sustainer Fin Set',
        stage: 2,
        mass: 0.35,
        count: 3,
        span: 0.08,
        rootChord: 0.14,
        tipChord: 0.05,
      },
      {
        id: 'p2-engine-upper',
        type: 'engine',
        name: 'Sustainer Motor',
        stage: 2,
        mass: 1.8,
        propellantMass: 2.6,
        burnTime: 3.2,
        avgThrust: 1400,
        thrustCurveShape: 'constant',
      },
      {
        id: 'p2-interstage',
        type: 'body-tube',
        name: 'Interstage Coupler',
        stage: 1,
        mass: 0.5,
        length: 0.2,
        diameter: 0.15,
      },
      {
        id: 'p2-body-lower',
        type: 'body-tube',
        name: 'Booster Airframe',
        stage: 1,
        mass: 2.2,
        length: 1.4,
        diameter: 0.15,
      },
      {
        id: 'p2-fins-lower',
        type: 'fins',
        name: 'Booster Fin Set',
        stage: 1,
        mass: 0.8,
        count: 4,
        span: 0.14,
        rootChord: 0.22,
        tipChord: 0.09,
      },
      {
        id: 'p2-engine-lower',
        type: 'engine',
        name: 'Booster Motor',
        stage: 1,
        mass: 4.2,
        propellantMass: 8.5,
        burnTime: 3.8,
        avgThrust: 5200,
        thrustCurveShape: 'regressive',
      },
    ],
  },
]

export function clonePreset(preset: RocketDesign): RocketDesign {
  return {
    id: `${preset.id}-${Date.now().toString(36)}`,
    name: preset.name,
    components: preset.components.map((c) => ({ ...c, id: `${c.id}-${Math.random().toString(36).slice(2, 7)}` })),
  }
}
